function f_coeffs=Total_Hazard_TE_Truncated_function(z, logZ, mu, sigma, sigmaMu, orderTE)
s=sigma.^2+sigmaMu.^2;
p=exp(1).^((-1/2).*((-1).*logZ+mu).^2.*s.^(-1)).*(2.*pi).^(-1/2).*s.^(-1/2);

num_pts_z = length(z);

if orderTE == 0
    
    f_coeffs = zeros(5, num_pts_z, orderTE+1);
    
    f_coeffs(1, :, 1)=(1/2).*(1+(-1).*erf(2.^(-1/2).*(logZ+(-1).*mu).*s.^(-1/2)));
    f_coeffs(2, :, 1)=p.*sigmaMu;
    f_coeffs(3, :, 1)=(1/2).*(logZ+(-1).*mu).*p.*s.^(-1).*sigmaMu.^2;
    f_coeffs(4, :, 1)=(-1/6).*p.*s.^(-2).*sigmaMu.^3.*((-1).*logZ.^2+2.*logZ.*mu+(-1).*mu.^2+ ...
        sigma.^2+sigmaMu.^2);
    f_coeffs(5, :, 1)=(1/24).*(logZ+(-1).*mu).*p.*s.^(-3).*sigmaMu.^4.*(logZ.^2+(-2).*logZ.* ...
        mu+mu.^2+(-3).*(sigma.^2+sigmaMu.^2));
end
if orderTE == 1
    
    f_coeffs = zeros(5, num_pts_z, orderTE+1);
    
    f_coeffs(1, :, 1)=(1/2).*(1+(-1).*erf(2.^(-1/2).*(logZ+(-1).*mu).*s.^(-1/2)));
    f_coeffs(2, :, 1)=p.*sigmaMu;
    f_coeffs(3, :, 1)=(1/2).*(logZ+(-1).*mu).*p.*s.^(-1).*sigmaMu.^2;
    f_coeffs(4, :, 1)=(-1/6).*p.*s.^(-2).*sigmaMu.^3.*((-1).*logZ.^2+2.*logZ.*mu+(-1).*mu.^2+ ...
        sigma.^2+sigmaMu.^2);
    f_coeffs(5, :, 1)=(1/24).*(logZ+(-1).*mu).*p.*s.^(-3).*sigmaMu.^4.*(logZ.^2+(-2).*logZ.* ...
        mu+mu.^2+(-3).*(sigma.^2+sigmaMu.^2));
    f_coeffs(1, :, 2)=(-1).*p.*z.^(-1);
    f_coeffs(2, :, 2)=((-1).*logZ+mu).*p.*s.^(-1).*sigmaMu.*z.^(-1);
    f_coeffs(3, :, 2)=(1/2).*p.*s.^(-2).*sigmaMu.^2.*((-1).*logZ.^2+2.*logZ.*mu+(-1).*mu.^2+ ...
        sigma.^2+sigmaMu.^2).*z.^(-1);
    f_coeffs(4, :, 2)=(-1/6).*(logZ+(-1).*mu).*p.*s.^(-3).*sigmaMu.^3.*(logZ.^2+(-2).*logZ.* ...
        mu+mu.^2+(-3).*(sigma.^2+sigmaMu.^2)).*z.^(-1);
    f_coeffs(5, :, 2)=(-1/24).*p.*s.^(-4).*sigmaMu.^4.*(logZ.^4+(-4).*logZ.^3.*mu+mu.^4+6.* ...
        logZ.^2.*(mu.^2+(-1).*sigma.^2+(-1).*sigmaMu.^2)+(-6).*mu.^2.*(sigma.^2+ ...
        sigmaMu.^2)+3.*(sigma.^2+sigmaMu.^2).^2+(-4).*logZ.*(mu.^3+(-3).*mu.*( ...
        sigma.^2+sigmaMu.^2))).*z.^(-1);
end
if orderTE == 2
    
    f_coeffs = zeros(5, num_pts_z, orderTE+1);
    
    
    f_coeffs(1, :, 1)=(1/2).*(1+(-1).*erf(2.^(-1/2).*(logZ+(-1).*mu).*s.^(-1/2)));
    f_coeffs(2, :, 1)=p.*sigmaMu;
    f_coeffs(3, :, 1)=(1/2).*(logZ+(-1).*mu).*p.*s.^(-1).*sigmaMu.^2;
    f_coeffs(4, :, 1)=(-1/6).*p.*s.^(-2).*sigmaMu.^3.*((-1).*logZ.^2+2.*logZ.*mu+(-1).*mu.^2+ ...
        sigma.^2+sigmaMu.^2);
    f_coeffs(5, :, 1)=(1/24).*(logZ+(-1).*mu).*p.*s.^(-3).*sigmaMu.^4.*(logZ.^2+(-2).*logZ.* ...
        mu+mu.^2+(-3).*(sigma.^2+sigmaMu.^2));
    f_coeffs(1, :, 2)=(-1).*p.*z.^(-1);
    f_coeffs(2, :, 2)=((-1).*logZ+mu).*p.*s.^(-1).*sigmaMu.*z.^(-1);
    f_coeffs(3, :, 2)=(1/2).*p.*s.^(-2).*sigmaMu.^2.*((-1).*logZ.^2+2.*logZ.*mu+(-1).*mu.^2+ ...
        sigma.^2+sigmaMu.^2).*z.^(-1);
    f_coeffs(4, :, 2)=(-1/6).*(logZ+(-1).*mu).*p.*s.^(-3).*sigmaMu.^3.*(logZ.^2+(-2).*logZ.* ...
        mu+mu.^2+(-3).*(sigma.^2+sigmaMu.^2)).*z.^(-1);
    f_coeffs(5, :, 2)=(-1/24).*p.*s.^(-4).*sigmaMu.^4.*(logZ.^4+(-4).*logZ.^3.*mu+mu.^4+6.* ...
        logZ.^2.*(mu.^2+(-1).*sigma.^2+(-1).*sigmaMu.^2)+(-6).*mu.^2.*(sigma.^2+ ...
        sigmaMu.^2)+3.*(sigma.^2+sigmaMu.^2).^2+(-4).*logZ.*(mu.^3+(-3).*mu.*( ...
        sigma.^2+sigmaMu.^2))).*z.^(-1);
    f_coeffs(1, :, 3)=(logZ+(-1).*mu).*p.*s.^(-1).*sigmaMu;
    f_coeffs(2, :, 3)=p.*s.^(-2).*(sigma.^4+(logZ+(-1).*mu).^2.*sigmaMu.^2+sigma.^2.* ...
        sigmaMu.^2);
    f_coeffs(3, :, 3)=(1/2).*(logZ+(-1).*mu).*p.*s.^(-3).*sigmaMu.*(2.*sigma.^4+sigma.^2.* ...
        sigmaMu.^2+sigmaMu.^2.*(logZ.^2+(-2).*logZ.*mu+mu.^2+(-1).*sigmaMu.^2)); ...
        
    f_coeffs(4, :, 3)=(-1/6).*p.*s.^(-4).*sigmaMu.^2.*((-1).*logZ.^4.*sigmaMu.^2+4.*logZ.^3.* ...
        mu.*sigmaMu.^2+4.*logZ.*mu.^3.*sigmaMu.^2+(-1).*mu.^4.*sigmaMu.^2+3.* ...
        sigma.^2.*(sigma.^2+sigmaMu.^2).^2+6.*logZ.*mu.*(sigma.^4+(-1).* ...
        sigmaMu.^4)+(-3).*mu.^2.*(sigma.^4+(-1).*sigmaMu.^4)+(-3).*logZ.^2.*( ...
        sigma.^4+2.*mu.^2.*sigmaMu.^2+(-1).*sigmaMu.^4));
    f_coeffs(5, :, 3)=(1/24).*((-1).*logZ+mu).*p.*s.^(-5).*sigmaMu.^3.*((-1).*logZ.^4.* ...
        sigmaMu.^2+4.*logZ.^3.*mu.*sigmaMu.^2+(-1).*mu.^4.*sigmaMu.^2+3.*(4.* ...
        sigma.^2+(-1).*sigmaMu.^2).*(sigma.^2+sigmaMu.^2).^2+4.*logZ.*mu.*(2.* ...
        sigma.^4+mu.^2.*sigmaMu.^2+(-1).*sigma.^2.*sigmaMu.^2+(-3).*sigmaMu.^4)+ ...
        mu.^2.*((-4).*sigma.^4+2.*sigma.^2.*sigmaMu.^2+6.*sigmaMu.^4)+logZ.^2.*( ...
        (-4).*sigma.^4+(-6).*mu.^2.*sigmaMu.^2+2.*sigma.^2.*sigmaMu.^2+6.* ...
        sigmaMu.^4));
end
if orderTE == 3
    
    f_coeffs = zeros(5, num_pts_z, orderTE+1);
    
    
    f_coeffs(1, :, 1)=(1/2).*(1+(-1).*erf(2.^(-1/2).*(logZ+(-1).*mu).*s.^(-1/2)));
    f_coeffs(2, :, 1)=p.*sigmaMu;
    f_coeffs(3, :, 1)=(1/2).*(logZ+(-1).*mu).*p.*s.^(-1).*sigmaMu.^2;
    f_coeffs(4, :, 1)=(-1/6).*p.*s.^(-2).*sigmaMu.^3.*((-1).*logZ.^2+2.*logZ.*mu+(-1).*mu.^2+ ...
        sigma.^2+sigmaMu.^2);
    f_coeffs(5, :, 1)=(1/24).*(logZ+(-1).*mu).*p.*s.^(-3).*sigmaMu.^4.*(logZ.^2+(-2).*logZ.* ...
        mu+mu.^2+(-3).*(sigma.^2+sigmaMu.^2));
    f_coeffs(1, :, 2)=(-1).*p.*z.^(-1);
    f_coeffs(2, :, 2)=((-1).*logZ+mu).*p.*s.^(-1).*sigmaMu.*z.^(-1);
    f_coeffs(3, :, 2)=(1/2).*p.*s.^(-2).*sigmaMu.^2.*((-1).*logZ.^2+2.*logZ.*mu+(-1).*mu.^2+ ...
        sigma.^2+sigmaMu.^2).*z.^(-1);
    f_coeffs(4, :, 2)=(-1/6).*(logZ+(-1).*mu).*p.*s.^(-3).*sigmaMu.^3.*(logZ.^2+(-2).*logZ.* ...
        mu+mu.^2+(-3).*(sigma.^2+sigmaMu.^2)).*z.^(-1);
    f_coeffs(5, :, 2)=(-1/24).*p.*s.^(-4).*sigmaMu.^4.*(logZ.^4+(-4).*logZ.^3.*mu+mu.^4+6.* ...
        logZ.^2.*(mu.^2+(-1).*sigma.^2+(-1).*sigmaMu.^2)+(-6).*mu.^2.*(sigma.^2+ ...
        sigmaMu.^2)+3.*(sigma.^2+sigmaMu.^2).^2+(-4).*logZ.*(mu.^3+(-3).*mu.*( ...
        sigma.^2+sigmaMu.^2))).*z.^(-1);
    f_coeffs(1, :, 3)=(logZ+(-1).*mu).*p.*s.^(-1).*sigmaMu;
    f_coeffs(2, :, 3)=p.*s.^(-2).*(sigma.^4+(logZ+(-1).*mu).^2.*sigmaMu.^2+sigma.^2.* ...
        sigmaMu.^2);
    f_coeffs(3, :, 3)=(1/2).*(logZ+(-1).*mu).*p.*s.^(-3).*sigmaMu.*(2.*sigma.^4+sigma.^2.* ...
        sigmaMu.^2+sigmaMu.^2.*(logZ.^2+(-2).*logZ.*mu+mu.^2+(-1).*sigmaMu.^2)); ...
        
    f_coeffs(4, :, 3)=(-1/6).*p.*s.^(-4).*sigmaMu.^2.*((-1).*logZ.^4.*sigmaMu.^2+4.*logZ.^3.* ...
        mu.*sigmaMu.^2+4.*logZ.*mu.^3.*sigmaMu.^2+(-1).*mu.^4.*sigmaMu.^2+3.* ...
        sigma.^2.*(sigma.^2+sigmaMu.^2).^2+6.*logZ.*mu.*(sigma.^4+(-1).* ...
        sigmaMu.^4)+(-3).*mu.^2.*(sigma.^4+(-1).*sigmaMu.^4)+(-3).*logZ.^2.*( ...
        sigma.^4+2.*mu.^2.*sigmaMu.^2+(-1).*sigmaMu.^4));
    f_coeffs(5, :, 3)=(1/24).*((-1).*logZ+mu).*p.*s.^(-5).*sigmaMu.^3.*((-1).*logZ.^4.* ...
        sigmaMu.^2+4.*logZ.^3.*mu.*sigmaMu.^2+(-1).*mu.^4.*sigmaMu.^2+3.*(4.* ...
        sigma.^2+(-1).*sigmaMu.^2).*(sigma.^2+sigmaMu.^2).^2+4.*logZ.*mu.*(2.* ...
        sigma.^4+mu.^2.*sigmaMu.^2+(-1).*sigma.^2.*sigmaMu.^2+(-3).*sigmaMu.^4)+ ...
        mu.^2.*((-4).*sigma.^4+2.*sigma.^2.*sigmaMu.^2+6.*sigmaMu.^4)+logZ.^2.*( ...
        (-4).*sigma.^4+(-6).*mu.^2.*sigmaMu.^2+2.*sigma.^2.*sigmaMu.^2+6.* ...
        sigmaMu.^4));
    f_coeffs(1, :, 4)=p.*s.^(-1).*(logZ+(-1).*mu+sigma.^2+sigmaMu.^2).*z.^(-2);
    f_coeffs(2, :, 4)=p.*s.^(-2).*sigmaMu.*(logZ.^2+mu.^2+(-1).*sigma.^2+(-1).*sigmaMu.^2+(-1) ...
        .*mu.*(sigma.^2+sigmaMu.^2)+logZ.*((-2).*mu+sigma.^2+sigmaMu.^2)).*z.^( ...
        -2);
    f_coeffs(3, :, 4)=(-1/2).*p.*s.^(-3).*sigmaMu.^2.*((-1).*logZ.^3+mu.^3+logZ.^2.*(3.*mu+( ...
        -1).*sigma.^2+(-1).*sigmaMu.^2)+(-3).*mu.*(sigma.^2+sigmaMu.^2)+(-1).* ...
        mu.^2.*(sigma.^2+sigmaMu.^2)+(sigma.^2+sigmaMu.^2).^2+logZ.*((-3).* ...
        mu.^2+3.*(sigma.^2+sigmaMu.^2)+2.*mu.*(sigma.^2+sigmaMu.^2))).*z.^(-2); ...
        
    f_coeffs(4, :, 4)=(1/6).*p.*s.^(-4).*sigmaMu.^3.*(logZ.^4+mu.^4+(-6).*mu.^2.*(sigma.^2+ ...
        sigmaMu.^2)+(-1).*mu.^3.*(sigma.^2+sigmaMu.^2)+3.*(sigma.^2+sigmaMu.^2) ...
        .^2+3.*mu.*(sigma.^2+sigmaMu.^2).^2+logZ.^3.*((-4).*mu+sigma.^2+ ...
        sigmaMu.^2)+logZ.^2.*(6.*mu.^2+(-6).*(sigma.^2+sigmaMu.^2)+(-3).*mu.*( ...
        sigma.^2+sigmaMu.^2))+logZ.*((-4).*mu.^3+12.*mu.*(sigma.^2+sigmaMu.^2)+ ...
        3.*mu.^2.*(sigma.^2+sigmaMu.^2)+(-3).*(sigma.^2+sigmaMu.^2).^2)).*z.^( ...
        -2);
    f_coeffs(5, :, 4)=(1/24).*p.*s.^(-5).*sigmaMu.^4.*(logZ.^5+(-1).*mu.^5+10.*mu.^3.*( ...
        sigma.^2+sigmaMu.^2)+mu.^4.*(sigma.^2+sigmaMu.^2)+(-15).*mu.*(sigma.^2+ ...
        sigmaMu.^2).^2+(-6).*mu.^2.*(sigma.^2+sigmaMu.^2).^2+3.*(sigma.^2+ ...
        sigmaMu.^2).^3+logZ.^4.*((-5).*mu+sigma.^2+sigmaMu.^2)+2.*logZ.^3.*(5.* ...
        mu.^2+(-5).*(sigma.^2+sigmaMu.^2)+(-2).*mu.*(sigma.^2+sigmaMu.^2))+(-2) ...
        .*logZ.^2.*(5.*mu.^3+(-15).*mu.*(sigma.^2+sigmaMu.^2)+(-3).*mu.^2.*( ...
        sigma.^2+sigmaMu.^2)+3.*(sigma.^2+sigmaMu.^2).^2)+logZ.*(5.*mu.^4+(-30) ...
        .*mu.^2.*(sigma.^2+sigmaMu.^2)+(-4).*mu.^3.*(sigma.^2+sigmaMu.^2)+15.*( ...
        sigma.^2+sigmaMu.^2).^2+12.*mu.*(sigma.^2+sigmaMu.^2).^2)).*z.^(-2);
end
if orderTE == 4
    
    f_coeffs = zeros(5, num_pts_z, orderTE+1);
    
    
    f_coeffs(1, :, 1)=(1/2).*(1+(-1).*erf(2.^(-1/2).*(logZ+(-1).*mu).*s.^(-1/2)));
    f_coeffs(2, :, 1)=p.*sigmaMu;
    f_coeffs(3, :, 1)=(1/2).*(logZ+(-1).*mu).*p.*s.^(-1).*sigmaMu.^2;
    f_coeffs(4, :, 1)=(-1/6).*p.*s.^(-2).*sigmaMu.^3.*((-1).*logZ.^2+2.*logZ.*mu+(-1).*mu.^2+ ...
        sigma.^2+sigmaMu.^2);
    f_coeffs(5, :, 1)=(1/24).*(logZ+(-1).*mu).*p.*s.^(-3).*sigmaMu.^4.*(logZ.^2+(-2).*logZ.* ...
        mu+mu.^2+(-3).*(sigma.^2+sigmaMu.^2));
    f_coeffs(1, :, 2)=(-1).*p.*z.^(-1);
    f_coeffs(2, :, 2)=((-1).*logZ+mu).*p.*s.^(-1).*sigmaMu.*z.^(-1);
    f_coeffs(3, :, 2)=(1/2).*p.*s.^(-2).*sigmaMu.^2.*((-1).*logZ.^2+2.*logZ.*mu+(-1).*mu.^2+ ...
        sigma.^2+sigmaMu.^2).*z.^(-1);
    f_coeffs(4, :, 2)=(-1/6).*(logZ+(-1).*mu).*p.*s.^(-3).*sigmaMu.^3.*(logZ.^2+(-2).*logZ.* ...
        mu+mu.^2+(-3).*(sigma.^2+sigmaMu.^2)).*z.^(-1);
    f_coeffs(5, :, 2)=(-1/24).*p.*s.^(-4).*sigmaMu.^4.*(logZ.^4+(-4).*logZ.^3.*mu+mu.^4+6.* ...
        logZ.^2.*(mu.^2+(-1).*sigma.^2+(-1).*sigmaMu.^2)+(-6).*mu.^2.*(sigma.^2+ ...
        sigmaMu.^2)+3.*(sigma.^2+sigmaMu.^2).^2+(-4).*logZ.*(mu.^3+(-3).*mu.*( ...
        sigma.^2+sigmaMu.^2))).*z.^(-1);
    f_coeffs(1, :, 3)=(logZ+(-1).*mu).*p.*s.^(-1).*sigmaMu;
    f_coeffs(2, :, 3)=p.*s.^(-2).*(sigma.^4+(logZ+(-1).*mu).^2.*sigmaMu.^2+sigma.^2.* ...
        sigmaMu.^2);
    f_coeffs(3, :, 3)=(1/2).*(logZ+(-1).*mu).*p.*s.^(-3).*sigmaMu.*(2.*sigma.^4+sigma.^2.* ...
        sigmaMu.^2+sigmaMu.^2.*(logZ.^2+(-2).*logZ.*mu+mu.^2+(-1).*sigmaMu.^2)); ...
        
    f_coeffs(4, :, 3)=(-1/6).*p.*s.^(-4).*sigmaMu.^2.*((-1).*logZ.^4.*sigmaMu.^2+4.*logZ.^3.* ...
        mu.*sigmaMu.^2+4.*logZ.*mu.^3.*sigmaMu.^2+(-1).*mu.^4.*sigmaMu.^2+3.* ...
        sigma.^2.*(sigma.^2+sigmaMu.^2).^2+6.*logZ.*mu.*(sigma.^4+(-1).* ...
        sigmaMu.^4)+(-3).*mu.^2.*(sigma.^4+(-1).*sigmaMu.^4)+(-3).*logZ.^2.*( ...
        sigma.^4+2.*mu.^2.*sigmaMu.^2+(-1).*sigmaMu.^4));
    f_coeffs(5, :, 3)=(1/24).*((-1).*logZ+mu).*p.*s.^(-5).*sigmaMu.^3.*((-1).*logZ.^4.* ...
        sigmaMu.^2+4.*logZ.^3.*mu.*sigmaMu.^2+(-1).*mu.^4.*sigmaMu.^2+3.*(4.* ...
        sigma.^2+(-1).*sigmaMu.^2).*(sigma.^2+sigmaMu.^2).^2+4.*logZ.*mu.*(2.* ...
        sigma.^4+mu.^2.*sigmaMu.^2+(-1).*sigma.^2.*sigmaMu.^2+(-3).*sigmaMu.^4)+ ...
        mu.^2.*((-4).*sigma.^4+2.*sigma.^2.*sigmaMu.^2+6.*sigmaMu.^4)+logZ.^2.*( ...
        (-4).*sigma.^4+(-6).*mu.^2.*sigmaMu.^2+2.*sigma.^2.*sigmaMu.^2+6.* ...
        sigmaMu.^4));
    f_coeffs(1, :, 4)=p.*s.^(-1).*(logZ+(-1).*mu+sigma.^2+sigmaMu.^2).*z.^(-2);
    f_coeffs(2, :, 4)=p.*s.^(-2).*sigmaMu.*(logZ.^2+mu.^2+(-1).*sigma.^2+(-1).*sigmaMu.^2+(-1) ...
        .*mu.*(sigma.^2+sigmaMu.^2)+logZ.*((-2).*mu+sigma.^2+sigmaMu.^2)).*z.^( ...
        -2);
    f_coeffs(3, :, 4)=(-1/2).*p.*s.^(-3).*sigmaMu.^2.*((-1).*logZ.^3+mu.^3+logZ.^2.*(3.*mu+( ...
        -1).*sigma.^2+(-1).*sigmaMu.^2)+(-3).*mu.*(sigma.^2+sigmaMu.^2)+(-1).* ...
        mu.^2.*(sigma.^2+sigmaMu.^2)+(sigma.^2+sigmaMu.^2).^2+logZ.*((-3).* ...
        mu.^2+3.*(sigma.^2+sigmaMu.^2)+2.*mu.*(sigma.^2+sigmaMu.^2))).*z.^(-2); ...
        
    f_coeffs(4, :, 4)=(1/6).*p.*s.^(-4).*sigmaMu.^3.*(logZ.^4+mu.^4+(-6).*mu.^2.*(sigma.^2+ ...
        sigmaMu.^2)+(-1).*mu.^3.*(sigma.^2+sigmaMu.^2)+3.*(sigma.^2+sigmaMu.^2) ...
        .^2+3.*mu.*(sigma.^2+sigmaMu.^2).^2+logZ.^3.*((-4).*mu+sigma.^2+ ...
        sigmaMu.^2)+logZ.^2.*(6.*mu.^2+(-6).*(sigma.^2+sigmaMu.^2)+(-3).*mu.*( ...
        sigma.^2+sigmaMu.^2))+logZ.*((-4).*mu.^3+12.*mu.*(sigma.^2+sigmaMu.^2)+ ...
        3.*mu.^2.*(sigma.^2+sigmaMu.^2)+(-3).*(sigma.^2+sigmaMu.^2).^2)).*z.^( ...
        -2);
    f_coeffs(5, :, 4)=(1/24).*p.*s.^(-5).*sigmaMu.^4.*(logZ.^5+(-1).*mu.^5+10.*mu.^3.*( ...
        sigma.^2+sigmaMu.^2)+mu.^4.*(sigma.^2+sigmaMu.^2)+(-15).*mu.*(sigma.^2+ ...
        sigmaMu.^2).^2+(-6).*mu.^2.*(sigma.^2+sigmaMu.^2).^2+3.*(sigma.^2+ ...
        sigmaMu.^2).^3+logZ.^4.*((-5).*mu+sigma.^2+sigmaMu.^2)+2.*logZ.^3.*(5.* ...
        mu.^2+(-5).*(sigma.^2+sigmaMu.^2)+(-2).*mu.*(sigma.^2+sigmaMu.^2))+(-2) ...
        .*logZ.^2.*(5.*mu.^3+(-15).*mu.*(sigma.^2+sigmaMu.^2)+(-3).*mu.^2.*( ...
        sigma.^2+sigmaMu.^2)+3.*(sigma.^2+sigmaMu.^2).^2)+logZ.*(5.*mu.^4+(-30) ...
        .*mu.^2.*(sigma.^2+sigmaMu.^2)+(-4).*mu.^3.*(sigma.^2+sigmaMu.^2)+15.*( ...
        sigma.^2+sigmaMu.^2).^2+12.*mu.*(sigma.^2+sigmaMu.^2).^2)).*z.^(-2);
    f_coeffs(1, :, 5)=p.*s.^(-2).*sigmaMu.*((-1).*logZ.^2+2.*logZ.*mu+(-1).*mu.^2+sigma.^2+ ...
        sigmaMu.^2).*z.^(-1);
    f_coeffs(2, :, 5)=(-1).*(logZ+(-1).*mu).*p.*s.^(-3).*(sigma.^4+(-1).*sigma.^2.*sigmaMu.^2+ ...
        sigmaMu.^2.*(logZ.^2+(-2).*logZ.*mu+mu.^2+(-2).*sigmaMu.^2)).*z.^(-1);
    f_coeffs(3, :, 5)=(-1/2).*p.*s.^(-4).*sigmaMu.*((-2).*sigma.^6+logZ.^4.*sigmaMu.^2+(-4).* ...
        logZ.^3.*mu.*sigmaMu.^2+mu.^4.*sigmaMu.^2+(-3).*sigma.^4.*sigmaMu.^2+ ...
        sigmaMu.^6+2.*mu.^2.*(sigma.^4+(-1).*sigma.^2.*sigmaMu.^2+(-2).* ...
        sigmaMu.^4)+(-4).*logZ.*mu.*(sigma.^4+mu.^2.*sigmaMu.^2+(-1).*sigma.^2.* ...
        sigmaMu.^2+(-2).*sigmaMu.^4)+2.*logZ.^2.*(sigma.^4+3.*mu.^2.*sigmaMu.^2+ ...
        (-1).*sigma.^2.*sigmaMu.^2+(-2).*sigmaMu.^4)).*z.^(-1);
    f_coeffs(4, :, 5)=(1/6).*((-1).*logZ+mu).*p.*s.^(-5).*sigmaMu.^2.*(logZ.^4.*sigmaMu.^2+( ...
        -4).*logZ.^3.*mu.*sigmaMu.^2+mu.^4.*sigmaMu.^2+(-3).*(3.*sigma.^2+(-2).* ...
        sigmaMu.^2).*(sigma.^2+sigmaMu.^2).^2+mu.^2.*(3.*sigma.^4+(-4).* ...
        sigma.^2.*sigmaMu.^2+(-7).*sigmaMu.^4)+logZ.^2.*(3.*sigma.^4+6.*mu.^2.* ...
        sigmaMu.^2+(-4).*sigma.^2.*sigmaMu.^2+(-7).*sigmaMu.^4)+2.*logZ.*mu.*(( ...
        -3).*sigma.^4+(-2).*mu.^2.*sigmaMu.^2+4.*sigma.^2.*sigmaMu.^2+7.* ...
        sigmaMu.^4)).*z.^(-1);
    f_coeffs(5, :, 5)=(-1/24).*p.*s.^(-6).*sigmaMu.^3.*(logZ.^6.*sigmaMu.^2+(-6).*logZ.^5.* ...
        mu.*sigmaMu.^2+mu.^6.*sigmaMu.^2+(-3).*mu.^2.*(8.*sigma.^2+(-7).* ...
        sigmaMu.^2).*(sigma.^2+sigmaMu.^2).^2+3.*(4.*sigma.^2+(-1).*sigmaMu.^2) ...
        .*(sigma.^2+sigmaMu.^2).^3+mu.^4.*(4.*sigma.^4+(-7).*sigma.^2.* ...
        sigmaMu.^2+(-11).*sigmaMu.^4)+(-4).*logZ.^3.*mu.*(4.*sigma.^4+5.*mu.^2.* ...
        sigmaMu.^2+(-7).*sigma.^2.*sigmaMu.^2+(-11).*sigmaMu.^4)+logZ.^4.*(4.* ...
        sigma.^4+15.*mu.^2.*sigmaMu.^2+(-7).*sigma.^2.*sigmaMu.^2+(-11).* ...
        sigmaMu.^4)+3.*logZ.^2.*(5.*mu.^4.*sigmaMu.^2+(-1).*(8.*sigma.^2+(-7).* ...
        sigmaMu.^2).*(sigma.^2+sigmaMu.^2).^2+2.*mu.^2.*(4.*sigma.^4+(-7).* ...
        sigma.^2.*sigmaMu.^2+(-11).*sigmaMu.^4))+logZ.*((-6).*mu.^5.*sigmaMu.^2+ ...
        6.*mu.*(8.*sigma.^2+(-7).*sigmaMu.^2).*(sigma.^2+sigmaMu.^2).^2+mu.^3.*( ...
        (-16).*sigma.^4+28.*sigma.^2.*sigmaMu.^2+44.*sigmaMu.^4))).*z.^(-1);
end
if orderTE == 5
    
    f_coeffs = zeros(5, num_pts_z, orderTE+1);
    
    
    f_coeffs(1, :, 1)=(1/2).*(1+(-1).*erf(2.^(-1/2).*(logZ+(-1).*mu).*s.^(-1/2)));
    f_coeffs(2, :, 1)=p.*sigmaMu;
    f_coeffs(3, :, 1)=(1/2).*(logZ+(-1).*mu).*p.*s.^(-1).*sigmaMu.^2;
    f_coeffs(4, :, 1)=(-1/6).*p.*s.^(-2).*sigmaMu.^3.*((-1).*logZ.^2+2.*logZ.*mu+(-1).*mu.^2+ ...
        sigma.^2+sigmaMu.^2);
    f_coeffs(5, :, 1)=(1/24).*(logZ+(-1).*mu).*p.*s.^(-3).*sigmaMu.^4.*(logZ.^2+(-2).*logZ.* ...
        mu+mu.^2+(-3).*(sigma.^2+sigmaMu.^2));
    f_coeffs(1, :, 2)=(-1).*p.*z.^(-1);
    f_coeffs(2, :, 2)=((-1).*logZ+mu).*p.*s.^(-1).*sigmaMu.*z.^(-1);
    f_coeffs(3, :, 2)=(1/2).*p.*s.^(-2).*sigmaMu.^2.*((-1).*logZ.^2+2.*logZ.*mu+(-1).*mu.^2+ ...
        sigma.^2+sigmaMu.^2).*z.^(-1);
    f_coeffs(4, :, 2)=(-1/6).*(logZ+(-1).*mu).*p.*s.^(-3).*sigmaMu.^3.*(logZ.^2+(-2).*logZ.* ...
        mu+mu.^2+(-3).*(sigma.^2+sigmaMu.^2)).*z.^(-1);
    f_coeffs(5, :, 2)=(-1/24).*p.*s.^(-4).*sigmaMu.^4.*(logZ.^4+(-4).*logZ.^3.*mu+mu.^4+6.* ...
        logZ.^2.*(mu.^2+(-1).*sigma.^2+(-1).*sigmaMu.^2)+(-6).*mu.^2.*(sigma.^2+ ...
        sigmaMu.^2)+3.*(sigma.^2+sigmaMu.^2).^2+(-4).*logZ.*(mu.^3+(-3).*mu.*( ...
        sigma.^2+sigmaMu.^2))).*z.^(-1);
    f_coeffs(1, :, 3)=(logZ+(-1).*mu).*p.*s.^(-1).*sigmaMu;
    f_coeffs(2, :, 3)=p.*s.^(-2).*(sigma.^4+(logZ+(-1).*mu).^2.*sigmaMu.^2+sigma.^2.* ...
        sigmaMu.^2);
    f_coeffs(3, :, 3)=(1/2).*(logZ+(-1).*mu).*p.*s.^(-3).*sigmaMu.*(2.*sigma.^4+sigma.^2.* ...
        sigmaMu.^2+sigmaMu.^2.*(logZ.^2+(-2).*logZ.*mu+mu.^2+(-1).*sigmaMu.^2)); ...
        
    f_coeffs(4, :, 3)=(-1/6).*p.*s.^(-4).*sigmaMu.^2.*((-1).*logZ.^4.*sigmaMu.^2+4.*logZ.^3.* ...
        mu.*sigmaMu.^2+4.*logZ.*mu.^3.*sigmaMu.^2+(-1).*mu.^4.*sigmaMu.^2+3.* ...
        sigma.^2.*(sigma.^2+sigmaMu.^2).^2+6.*logZ.*mu.*(sigma.^4+(-1).* ...
        sigmaMu.^4)+(-3).*mu.^2.*(sigma.^4+(-1).*sigmaMu.^4)+(-3).*logZ.^2.*( ...
        sigma.^4+2.*mu.^2.*sigmaMu.^2+(-1).*sigmaMu.^4));
    f_coeffs(5, :, 3)=(1/24).*((-1).*logZ+mu).*p.*s.^(-5).*sigmaMu.^3.*((-1).*logZ.^4.* ...
        sigmaMu.^2+4.*logZ.^3.*mu.*sigmaMu.^2+(-1).*mu.^4.*sigmaMu.^2+3.*(4.* ...
        sigma.^2+(-1).*sigmaMu.^2).*(sigma.^2+sigmaMu.^2).^2+4.*logZ.*mu.*(2.* ...
        sigma.^4+mu.^2.*sigmaMu.^2+(-1).*sigma.^2.*sigmaMu.^2+(-3).*sigmaMu.^4)+ ...
        mu.^2.*((-4).*sigma.^4+2.*sigma.^2.*sigmaMu.^2+6.*sigmaMu.^4)+logZ.^2.*( ...
        (-4).*sigma.^4+(-6).*mu.^2.*sigmaMu.^2+2.*sigma.^2.*sigmaMu.^2+6.* ...
        sigmaMu.^4));
    f_coeffs(1, :, 4)=p.*s.^(-1).*(logZ+(-1).*mu+sigma.^2+sigmaMu.^2).*z.^(-2);
    f_coeffs(2, :, 4)=p.*s.^(-2).*sigmaMu.*(logZ.^2+mu.^2+(-1).*sigma.^2+(-1).*sigmaMu.^2+(-1) ...
        .*mu.*(sigma.^2+sigmaMu.^2)+logZ.*((-2).*mu+sigma.^2+sigmaMu.^2)).*z.^( ...
        -2);
    f_coeffs(3, :, 4)=(-1/2).*p.*s.^(-3).*sigmaMu.^2.*((-1).*logZ.^3+mu.^3+logZ.^2.*(3.*mu+( ...
        -1).*sigma.^2+(-1).*sigmaMu.^2)+(-3).*mu.*(sigma.^2+sigmaMu.^2)+(-1).* ...
        mu.^2.*(sigma.^2+sigmaMu.^2)+(sigma.^2+sigmaMu.^2).^2+logZ.*((-3).* ...
        mu.^2+3.*(sigma.^2+sigmaMu.^2)+2.*mu.*(sigma.^2+sigmaMu.^2))).*z.^(-2); ...
        
    f_coeffs(4, :, 4)=(1/6).*p.*s.^(-4).*sigmaMu.^3.*(logZ.^4+mu.^4+(-6).*mu.^2.*(sigma.^2+ ...
        sigmaMu.^2)+(-1).*mu.^3.*(sigma.^2+sigmaMu.^2)+3.*(sigma.^2+sigmaMu.^2) ...
        .^2+3.*mu.*(sigma.^2+sigmaMu.^2).^2+logZ.^3.*((-4).*mu+sigma.^2+ ...
        sigmaMu.^2)+logZ.^2.*(6.*mu.^2+(-6).*(sigma.^2+sigmaMu.^2)+(-3).*mu.*( ...
        sigma.^2+sigmaMu.^2))+logZ.*((-4).*mu.^3+12.*mu.*(sigma.^2+sigmaMu.^2)+ ...
        3.*mu.^2.*(sigma.^2+sigmaMu.^2)+(-3).*(sigma.^2+sigmaMu.^2).^2)).*z.^( ...
        -2);
    f_coeffs(5, :, 4)=(1/24).*p.*s.^(-5).*sigmaMu.^4.*(logZ.^5+(-1).*mu.^5+10.*mu.^3.*( ...
        sigma.^2+sigmaMu.^2)+mu.^4.*(sigma.^2+sigmaMu.^2)+(-15).*mu.*(sigma.^2+ ...
        sigmaMu.^2).^2+(-6).*mu.^2.*(sigma.^2+sigmaMu.^2).^2+3.*(sigma.^2+ ...
        sigmaMu.^2).^3+logZ.^4.*((-5).*mu+sigma.^2+sigmaMu.^2)+2.*logZ.^3.*(5.* ...
        mu.^2+(-5).*(sigma.^2+sigmaMu.^2)+(-2).*mu.*(sigma.^2+sigmaMu.^2))+(-2) ...
        .*logZ.^2.*(5.*mu.^3+(-15).*mu.*(sigma.^2+sigmaMu.^2)+(-3).*mu.^2.*( ...
        sigma.^2+sigmaMu.^2)+3.*(sigma.^2+sigmaMu.^2).^2)+logZ.*(5.*mu.^4+(-30) ...
        .*mu.^2.*(sigma.^2+sigmaMu.^2)+(-4).*mu.^3.*(sigma.^2+sigmaMu.^2)+15.*( ...
        sigma.^2+sigmaMu.^2).^2+12.*mu.*(sigma.^2+sigmaMu.^2).^2)).*z.^(-2);
    f_coeffs(1, :, 5)=p.*s.^(-2).*sigmaMu.*((-1).*logZ.^2+2.*logZ.*mu+(-1).*mu.^2+sigma.^2+ ...
        sigmaMu.^2).*z.^(-1);
    f_coeffs(2, :, 5)=(-1).*(logZ+(-1).*mu).*p.*s.^(-3).*(sigma.^4+(-1).*sigma.^2.*sigmaMu.^2+ ...
        sigmaMu.^2.*(logZ.^2+(-2).*logZ.*mu+mu.^2+(-2).*sigmaMu.^2)).*z.^(-1);
    f_coeffs(3, :, 5)=(-1/2).*p.*s.^(-4).*sigmaMu.*((-2).*sigma.^6+logZ.^4.*sigmaMu.^2+(-4).* ...
        logZ.^3.*mu.*sigmaMu.^2+mu.^4.*sigmaMu.^2+(-3).*sigma.^4.*sigmaMu.^2+ ...
        sigmaMu.^6+2.*mu.^2.*(sigma.^4+(-1).*sigma.^2.*sigmaMu.^2+(-2).* ...
        sigmaMu.^4)+(-4).*logZ.*mu.*(sigma.^4+mu.^2.*sigmaMu.^2+(-1).*sigma.^2.* ...
        sigmaMu.^2+(-2).*sigmaMu.^4)+2.*logZ.^2.*(sigma.^4+3.*mu.^2.*sigmaMu.^2+ ...
        (-1).*sigma.^2.*sigmaMu.^2+(-2).*sigmaMu.^4)).*z.^(-1);
    f_coeffs(4, :, 5)=(1/6).*((-1).*logZ+mu).*p.*s.^(-5).*sigmaMu.^2.*(logZ.^4.*sigmaMu.^2+( ...
        -4).*logZ.^3.*mu.*sigmaMu.^2+mu.^4.*sigmaMu.^2+(-3).*(3.*sigma.^2+(-2).* ...
        sigmaMu.^2).*(sigma.^2+sigmaMu.^2).^2+mu.^2.*(3.*sigma.^4+(-4).* ...
        sigma.^2.*sigmaMu.^2+(-7).*sigmaMu.^4)+logZ.^2.*(3.*sigma.^4+6.*mu.^2.* ...
        sigmaMu.^2+(-4).*sigma.^2.*sigmaMu.^2+(-7).*sigmaMu.^4)+2.*logZ.*mu.*(( ...
        -3).*sigma.^4+(-2).*mu.^2.*sigmaMu.^2+4.*sigma.^2.*sigmaMu.^2+7.* ...
        sigmaMu.^4)).*z.^(-1);
    f_coeffs(5, :, 5)=(-1/24).*p.*s.^(-6).*sigmaMu.^3.*(logZ.^6.*sigmaMu.^2+(-6).*logZ.^5.* ...
        mu.*sigmaMu.^2+mu.^6.*sigmaMu.^2+(-3).*mu.^2.*(8.*sigma.^2+(-7).* ...
        sigmaMu.^2).*(sigma.^2+sigmaMu.^2).^2+3.*(4.*sigma.^2+(-1).*sigmaMu.^2) ...
        .*(sigma.^2+sigmaMu.^2).^3+mu.^4.*(4.*sigma.^4+(-7).*sigma.^2.* ...
        sigmaMu.^2+(-11).*sigmaMu.^4)+(-4).*logZ.^3.*mu.*(4.*sigma.^4+5.*mu.^2.* ...
        sigmaMu.^2+(-7).*sigma.^2.*sigmaMu.^2+(-11).*sigmaMu.^4)+logZ.^4.*(4.* ...
        sigma.^4+15.*mu.^2.*sigmaMu.^2+(-7).*sigma.^2.*sigmaMu.^2+(-11).* ...
        sigmaMu.^4)+3.*logZ.^2.*(5.*mu.^4.*sigmaMu.^2+(-1).*(8.*sigma.^2+(-7).* ...
        sigmaMu.^2).*(sigma.^2+sigmaMu.^2).^2+2.*mu.^2.*(4.*sigma.^4+(-7).* ...
        sigma.^2.*sigmaMu.^2+(-11).*sigmaMu.^4))+logZ.*((-6).*mu.^5.*sigmaMu.^2+ ...
        6.*mu.*(8.*sigma.^2+(-7).*sigmaMu.^2).*(sigma.^2+sigmaMu.^2).^2+mu.^3.*( ...
        (-16).*sigma.^4+28.*sigma.^2.*sigmaMu.^2+44.*sigmaMu.^4))).*z.^(-1);
    f_coeffs(1, :, 6)=(logZ+(-1).*mu).*p.*s.^(-3).*(sigma.^4+(-1).*sigma.^2.*sigmaMu.^2+ ...
        sigmaMu.^2.*(logZ.^2+(-2).*logZ.*mu+mu.^2+(-2).*sigmaMu.^2));
    f_coeffs(2, :, 6)=p.*s.^(-4).*sigmaMu.*(logZ.^4.*sigmaMu.^2+(-4).*logZ.^3.*mu.*sigmaMu.^2+ ...
        mu.^4.*sigmaMu.^2+(-3).*sigma.^2.*(sigma.^2+sigmaMu.^2).^2+3.*mu.^2.*( ...
        sigma.^4+(-1).*sigmaMu.^4)+3.*logZ.^2.*(sigma.^4+2.*mu.^2.*sigmaMu.^2+( ...
        -1).*sigmaMu.^4)+logZ.*((-6).*mu.*sigma.^4+(-4).*mu.^3.*sigmaMu.^2+6.* ...
        mu.*sigmaMu.^4));
    f_coeffs(3, :, 6)=(1/2).*(logZ+(-1).*mu).*p.*s.^(-5).*(2.*sigma.^8+(-7).*sigma.^6.* ...
        sigmaMu.^2+(-7).*sigma.^2.*sigmaMu.^6+sigma.^4.*sigmaMu.^2.*(5.*logZ.^2+ ...
        (-10).*logZ.*mu+5.*mu.^2+(-18).*sigmaMu.^2)+sigmaMu.^4.*(logZ.^4+(-4).* ...
        logZ.^3.*mu+mu.^4+(-5).*mu.^2.*sigmaMu.^2+2.*sigmaMu.^4+logZ.^2.*(6.* ...
        mu.^2+(-5).*sigmaMu.^2)+logZ.*((-4).*mu.^3+10.*mu.*sigmaMu.^2)));
    f_coeffs(4, :, 6)=(1/6).*p.*s.^(-6).*sigmaMu.*(logZ.^6.*sigmaMu.^4+(-6).*logZ.^5.*mu.* ...
        sigmaMu.^4+mu.^6.*sigmaMu.^4+(-3).*sigma.^2.*(2.*sigma.^2+(-3).* ...
        sigmaMu.^2).*(sigma.^2+sigmaMu.^2).^3+(-4).*logZ.^3.*mu.*sigmaMu.^2.*( ...
        7.*sigma.^4+5.*mu.^2.*sigmaMu.^2+(-1).*sigma.^2.*sigmaMu.^2+(-8).* ...
        sigmaMu.^4)+3.*mu.^2.*(sigma.^2+sigmaMu.^2).^2.*(2.*sigma.^4+(-10).* ...
        sigma.^2.*sigmaMu.^2+3.*sigmaMu.^4)+mu.^4.*(7.*sigma.^4.*sigmaMu.^2+(-1) ...
        .*sigma.^2.*sigmaMu.^4+(-8).*sigmaMu.^6)+logZ.^4.*(7.*sigma.^4.* ...
        sigmaMu.^2+15.*mu.^2.*sigmaMu.^4+(-1).*sigma.^2.*sigmaMu.^4+(-8).* ...
        sigmaMu.^6)+3.*logZ.^2.*(2.*sigma.^8+(-6).*sigma.^6.*sigmaMu.^2+5.* ...
        mu.^4.*sigmaMu.^4+(-16).*mu.^2.*sigmaMu.^6+3.*sigmaMu.^8+(-2).* ...
        sigma.^2.*sigmaMu.^4.*(mu.^2+2.*sigmaMu.^2)+sigma.^4.*(14.*mu.^2.* ...
        sigmaMu.^2+(-15).*sigmaMu.^4))+2.*logZ.*mu.*((-6).*sigma.^8+18.* ...
        sigma.^6.*sigmaMu.^2+(-3).*mu.^4.*sigmaMu.^4+16.*mu.^2.*sigmaMu.^6+(-9) ...
        .*sigmaMu.^8+2.*sigma.^2.*sigmaMu.^4.*(mu.^2+6.*sigmaMu.^2)+sigma.^4.*(( ...
        -14).*mu.^2.*sigmaMu.^2+45.*sigmaMu.^4)));
    f_coeffs(5, :, 6)=(1/24).*(logZ+(-1).*mu).*p.*s.^(-7).*sigmaMu.^2.*(logZ.^6.*sigmaMu.^4+( ...
        -6).*logZ.^5.*mu.*sigmaMu.^4+mu.^6.*sigmaMu.^4+(-4).*logZ.^3.*mu.* ...
        sigmaMu.^2.*(9.*sigma.^4+5.*mu.^2.*sigmaMu.^2+(-3).*sigma.^2.* ...
        sigmaMu.^2+(-12).*sigmaMu.^4)+(-3).*(sigma.^2+sigmaMu.^2).^3.*(12.* ...
        sigma.^4+(-21).*sigma.^2.*sigmaMu.^2+2.*sigmaMu.^4)+3.*mu.^2.*(sigma.^2+ ...
        sigmaMu.^2).^2.*(4.*sigma.^4+(-22).*sigma.^2.*sigmaMu.^2+9.*sigmaMu.^4)+ ...
        3.*mu.^4.*(3.*sigma.^4.*sigmaMu.^2+(-1).*sigma.^2.*sigmaMu.^4+(-4).* ...
        sigmaMu.^6)+3.*logZ.^4.*(3.*sigma.^4.*sigmaMu.^2+5.*mu.^2.*sigmaMu.^4+( ...
        -1).*sigma.^2.*sigmaMu.^4+(-4).*sigmaMu.^6)+(-6).*logZ.*mu.*(4.* ...
        sigma.^8+(-14).*sigma.^6.*sigmaMu.^2+(-2).*sigma.^2.*sigmaMu.^4.*(mu.^2+ ...
        2.*sigmaMu.^2)+sigma.^4.*(6.*mu.^2.*sigmaMu.^2+(-31).*sigmaMu.^4)+ ...
        sigmaMu.^4.*(mu.^4+(-8).*mu.^2.*sigmaMu.^2+9.*sigmaMu.^4))+3.*logZ.^2.*( ...
        4.*sigma.^8+(-14).*sigma.^6.*sigmaMu.^2+5.*mu.^4.*sigmaMu.^4+(-24).* ...
        mu.^2.*sigmaMu.^6+9.*sigmaMu.^8+sigma.^4.*(18.*mu.^2.*sigmaMu.^2+(-31).* ...
        sigmaMu.^4)+(-2).*sigma.^2.*(3.*mu.^2.*sigmaMu.^4+2.*sigmaMu.^6)));
end
